add autoscaling_group
mnkap/terraform-aws pull request #15
Opened 2022-09-20 12:15 UTC by mnkap

2022-09-20 13:34 UTC, vladimirmukhin requested changes

2022-09-20 13:34 UTC, vladimirmukhin commented on level1/network.tf
> +  count             = length(var.public_cidr)
count should always be the first argument and also should be separated by a newline from other arguments

2022-09-20 13:34 UTC, vladimirmukhin commented on level1/network.tf
> +  count             = length(var.private_cidr)
count should always be the first argument and also should be separated by a newline from other arguments

2022-09-20 13:34 UTC, vladimirmukhin commented on level1/network.tf
> +  availability_zone = data.aws_availability_zones.available.names[1]
```suggestion
  availability_zone = data.aws_availability_zones.available.names[count.index]
```

2022-09-20 13:34 UTC, vladimirmukhin commented on level1/network.tf
> +  availability_zone = data.aws_availability_zones.available.names[0]
```suggestion
  availability_zone = data.aws_availability_zones.available.names[count.index]
```

2022-09-20 13:34 UTC, vladimirmukhin commented on level1/network.tf
> +}
```suggestion
  state = "available"
}
```

2022-09-20 13:34 UTC, vladimirmukhin commented on level2/alb.tf
> +
Why did you add this newline?

2022-09-20 13:34 UTC, vladimirmukhin commented on level2/asg.tf
> +  key_name        = "Main"
```suggestion
  key_name        = "main"
```

2022-09-20 13:34 UTC, vladimirmukhin commented on level2/asg.tf
> +  vpc_zone_identifier  = data.terraform_remote_state.level1.outputs.private_subnet_id
It will create all your instances in a single availability zone. You need instances to span multiple availability zones

2022-09-20 13:50 UTC, mnkap commented on level2/asg.tf
> +  key_name        = "Main"
The key name is valid

2022-09-20 14:12 UTC, mnkap commented on level2/asg.tf
> +  vpc_zone_identifier  = data.terraform_remote_state.level1.outputs.private_subnet_id
`vpc_zone_identifier  = [data.terraform_remote_state.level1.outputs.private_subnet_id, data.terraform_remote_state.level1.outputs.public_subnet_id]`

2022-09-20 15:06 UTC, vladimirmukhin commented on level2/asg.tf
> +  key_name        = "Main"
Please use lowercase

2022-09-22 14:29 UTC, vladimirmukhin approved these changes

2022-09-22 14:31 UTC, merged