Create VPC
mnkap/terraform-aws pull request #2
Opened 2022-07-31 10:50 UTC by mnkap

2022-07-31 14:29 UTC, vladimirmukhin requested changes

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  }
}
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  }
}
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  }
}
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  }
}
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
```suggestion
  }
}
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +}
Please end each file with a blank newline

2022-07-31 14:29 UTC, vladimirmukhin commented on provider.tf
> +}
Please end each file with a blank newline

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +resource "aws_route_table_association" "private0" {
```suggestion
}

resource "aws_route_table_association" "private0" {
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +resource "aws_route_table" "private0" {
```suggestion
}

resource "aws_route_table" "private0" {
```

2022-07-31 14:29 UTC, vladimirmukhin commented on main.tf
> +resource "aws_route_table" "public" {
```suggestion
}

resource "aws_route_table" "public" {
```

2022-07-31 14:30 UTC, vladimirmukhin requested changes
please run `terraform fmt` so terraform will automatically fix some code style mistakes and commit the result.

You can read more about terraform fmt here: https://www.terraform.io/cli/commands/fmt

2022-08-01 16:23 UTC, vladimirmukhin approved these changes

2022-08-01 16:38 UTC, mnkap commented
Deploy VPC

2022-08-01 16:38 UTC, mnkap commented
Deploy VPC

2022-08-01 16:40 UTC, merged